//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBOSysTacV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddonDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AddonDetail()
        {
            this.BookAddonsDetails = new HashSet<BookAddonsDetail>();
        }
    
        public int addonId { get; set; }
        public Nullable<int> addoncatId { get; set; }
        public Nullable<int> deptId { get; set; }
        public string addondescription { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> amount { get; set; }
    
        public virtual AddonCategory AddonCategory { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAddonsDetail> BookAddonsDetails { get; set; }
    }
}
