//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBOSysTacV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_OtherCharge
    {
        public int ch_Id { get; set; }
        public int trn_Id { get; set; }
        public string ch_desc { get; set; }
        public string note { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
