//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBOSysTacV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAddonsDetail
    {
        public int addondetail_Id { get; set; }
        public Nullable<int> bookaddonNo { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> addonId { get; set; }
    
        public virtual BookingAddon BookingAddon { get; set; }
        public virtual AddonDetail AddonDetail { get; set; }
    }
}
