//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBOSysTacV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingAddon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingAddon()
        {
            this.BookAddonsDetails = new HashSet<BookAddonsDetail>();
        }
    
        public int bookaddonNo { get; set; }
        public Nullable<int> trn_Id { get; set; }
        public string Addondesc { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAddonsDetail> BookAddonsDetails { get; set; }
        public virtual Booking Booking { get; set; }
    }
}
